### PR TITLE
🏅 Vet clinic database: create animals table 🏅

### PR DESCRIPTION
**Pull request by kambereBr**
Project Requirements: https://github.com/microverseinc/curriculum-databases/blob/main/db-structure/vet_clinic_create_tables.md
## 📝 General requirements

- ✅ Used the correct GitFlow.
- ✅ Created a database named `vet_clinic`
- ✅ Created a table named `animals` with the  columns: `id`, `name`, `date_of_birth`, `escape_attempts`, `neutered`, `weight_kg`
- ✅ Inserted data into the `animals` table
- ✅ Wrote the following queries that : 
1. Find all animals whose name ends in `mon`

microverse-sql-01

2. List the name of all animals born between `2016` and `2019`

microverse-sql-02

3. List the name of all animals that are `neutered` and have `less than 3 escape attempts`

microverse-sql-03

4. List the date of birth of all animals named either `Agumon` or `Pikachu`.

microverse-sql-04

5. List name and escape attempts of animals that weigh `more than 10.5kg`

microverse-sql-05

6. Find all animals that are `neutered`.

microverse-sql-06

7. Find all animals `not named Gabumon`.

microverse-sql-07

8. Find all animals with a weight `between 10.4kg and 17.3kg` (including the animals with the weights that `equals precisely 10.4kg or 17.3kg`)

microverse-sql-08

### CODE REVIEW

**Review by ridwanediallo — CHANGES_REQUESTED** [review]
# Changes Required ♻️
## Hi @kambereBr , 
AlmostThereReachGIF

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## (Highlights) Good Points: :+1:
- You documented your work professionally. ✔
- You used GitHub flow correctly. ✔
- Awesome job, creation the animal table, inserting the data and addin the queries. ✔


## Required Changes ♻️

- [ ] Well done creating the table, inserting the data and adding the queries. However, I have some suggesting about the readme file to make to more professional. 

1.  Please ensure to update the tect stack section to just the technologies you used in the project. :point_down: 
Screenshot from 2023-09-18 23-39-14

2. I kindly would suggest you to remove the deployment section because I think it's not concern by the project.  :point_down: 
Screenshot from 2023-09-18 23-40-43




## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by kambereBr** [comment]
Dear @ridwanediallo, thanks for your review 👏

**Review by divinecharlotte — APPROVED** [review]
# Hello @kambereBr     😃 🥳 🎉 🎈 

Great Job 😄 👏 You've done it. Your project is complete!  There is nothing else to say other than... it's time to merge it 👍🏻 ✅ 
### To Highlight 💯

- Good implementation of the required changes✔️
- Descriptive pr✔️






## Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by kambereBr** [comment]
Thanks dear @divinecharlotte 👏

**Pull request merged**
